name: flutter_hw_1
description: "Кототиндер. Приложение для лайка котиков."

homepage: https://github.com/azinhoxx/flutter_hw_1
repository: https://github.com/azinhoxx/flutter_hw_1
documentation: https://github.com/azinhoxx/flutter_hw_1

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_card_swiper: ^7.0.2
  http: ^1.3.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/paw_loading_icon.svg

  fonts:
    - family: CVIcons
      fonts:
        - asset: icons/CVIcons.ttf