name: cat_tinder
description: "CatTinder. An app for liking cats."

homepage: https://github.com/azinhoxx/cat_tinder
repository: https://github.com/azinhoxx/cat_tinder
documentation: https://github.com/azinhoxx/cat_tinder

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_card_swiper: ^7.0.2
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  provider: ^6.1.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  photo_view: ^0.15.0
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  rename: ^3.0.2
  # dart run inno_bundle:build --release
  inno_bundle: ^0.9.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/paw_loading_icon.svg

  fonts:
    - family: CVIcons
      fonts:
        - asset: icons/CVIcons.ttf
    - family: 'Sour Gummy'
      fonts:
        - asset: fonts/SourGummy-Bold.ttf
          weight: 700
    - family: 'Montserrat'
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
inno_bundle:
  id: 0a9a47d0-02b3-11f0-bc70-f72afea39321
  publisher: dimas