name: flutter_hw_1
description: "CatTinder. An app for liking cats."

homepage: https://github.com/azinhoxx/flutter_hw_1
repository: https://github.com/azinhoxx/flutter_hw_1
documentation: https://github.com/azinhoxx/flutter_hw_1

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_card_swiper: ^7.0.2
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  provider: ^6.1.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  photo_view: ^0.15.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  rename: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/paw_loading_icon.svg

  fonts:
    - family: CVIcons
      fonts:
        - asset: icons/CVIcons.ttf
    - family: 'Sour Gummy'
      fonts:
        - asset: fonts/SourGummy-Bold.ttf
          weight: 700
    - family: 'Montserrat'
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

# run: flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: assets/icons/app_icon.png
  android: true
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#93AEB5"
  windows:
    generate: true
    image_path: assets/icons/rounded_app_icon.png
    icon_size: 256
  macos:
    generate: true
  web:
    generate: false

# run: dart run flutter_native_splash:create
flutter_native_splash:
  color: "#93AEB5"
  android_12:
    color: "#93AEB5"
  color_android: "#93AEB5"
  color_ios: "#93AEB5"
  color_web: "#93AEB5"
  image_web: assets/icons/app_icon_masked_324.png