name: cat_tinder
description: "CatTinder. An app for liking cats."

homepage: https://github.com/azinhoxx/cat_tinder
repository: https://github.com/azinhoxx/cat_tinder
documentation: https://github.com/azinhoxx/cat_tinder

publish_to: 'none'

version: 1.1.1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_card_swiper: ^7.0.2
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  photo_view: ^0.15.0
  flutter_native_splash: ^2.4.5
  get_it: ^8.0.3
  equatable: ^2.0.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  injectable: ^2.5.0
  connectivity_plus: ^6.1.3
  injectable_generator: ^2.7.0
  go_router: ^14.8.1
  flutter_bloc: ^9.1.0
  animations: ^2.0.11
  intl: ^0.20.2
  vibration: ^3.1.3

dev_dependencies:
  # dart run inno_bundle:build --release
  inno_bundle: ^0.9.0

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  rename: ^3.0.2
  build_runner: ^2.4.15
  freezed: ^2.4.6
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/paw_loading_icon.svg
    - assets/icons/cat_avatar_placeholder.png

  fonts:
    - family: CVIcons
      fonts:
        - asset: icons/CVIcons.ttf
    - family: 'Sour Gummy'
      fonts:
        - asset: fonts/SourGummy-Bold.ttf
          weight: 700
    - family: 'TinkoffSans'
      fonts:
        - asset: fonts/TinkoffSans-Regular.ttf
          weight: 400
        - asset: fonts/TinkoffSans-Medium.ttf
          weight: 600
        - asset: fonts/TinkoffSans-Bold.ttf
          weight: 700
inno_bundle:
  id: 0a9a47d0-02b3-11f0-bc70-f72afea39321
  publisher: dimas