name: Flutter Analyze & Format Check & Tests

on:
  push:
    branches: [ main ]

jobs:
  analyze-and-format:
    name: Analyze & Format & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create .env
        run: |
          echo "CATS_API_KEY=${{ secrets.CATS_API_KEY }}" >> .env

      - name: Install dependencies
        run: flutter pub get

      - name: Run flutter analyze
        run: flutter analyze

      - name: Check Dart format
        run: |
          dart format --output=none --set-exit-if-changed .

      - name: Run tests
        run: flutter test
