name: Auto Release Flutter

permissions:
  contents: write

on: 
  workflow_run:
    workflows: ["Flutter Analyze & Format Check"]
    types:
      - completed
  
jobs:
  build-android:
    name: Build Android (${{ matrix.build-type }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-type: [apk, appbundle, apk-split]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
  
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create .env
        run: |
          echo "CATS_API_KEY=${{ secrets.CATS_API_KEY }}" >> .env

      - name: Install dependencies
        run: flutter pub get
        
      - name: Build APK
        if: matrix.build-type == 'apk'
        run: flutter build apk --release

      - name: Build AppBundle
        if: matrix.build-type == 'appbundle'
        run: flutter build appbundle --release

      - name: Build Split APKs
        if: matrix.build-type == 'apk-split'
        run: flutter build apk --release --split-per-abi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ matrix.build-type }}
          path: |
            ${{ matrix.build-type == 'apk' && 'build/app/outputs/flutter-apk/app-release.apk' || '' }}
            ${{ matrix.build-type == 'appbundle' && 'build/app/outputs/bundle/release/app-release.aab' || '' }}
            ${{ matrix.build-type == 'apk-split' && 'build/app/outputs/flutter-apk/*.apk' || '' }}

  build-windows-portable:
    name: Build Windows Portable
    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Create .env
      run: |
        echo "CATS_API_KEY=${{ secrets.CATS_API_KEY }}" >> .env

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows
      run: flutter build windows

    - name: Upload Windows Build
      uses: actions/upload-artifact@v4
      with:
        name: windows-portable
        path: build/windows/x64/runner/Release/

  build-windows-installer:
    name: Build Windows Installer
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create .env file
        run: |
          echo "CATS_API_KEY=${{ secrets.CATS_API_KEY }}" >> .env

      - name: Install dependencies
        run: flutter pub get

      - name: Install winget
        uses: Cyberboss/install-winget@v1

      - name: Install InnoSetup
        run: winget install --source winget --id JRSoftware.InnoSetup --exact --accept-source-agreements --accept-package-agreements

      - name: Build Windows
        run: dart run inno_bundle:build --release

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: build/windows/x64/installer/Release/*.exe

  release:
    needs: [build-android, build-windows-portable, build-windows-installer]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: release/android/

      - name: Download Android AppBundle
        uses: actions/download-artifact@v4
        with:
          name: android-appbundle
          path: release/android/

      - name: Download Split APKs
        uses: actions/download-artifact@v4
        with:
          name: android-apk-split
          path: release/android/split/

      - name: Download Web Build
        uses: actions/download-artifact@v4
        with:
          name: web
          path: release/web/

      - name: Download Windows Portable
        uses: actions/download-artifact@v4
        with:
          name: windows-portable
          path: release/windows/portable/

      - name: Download Windows Installer
        uses: actions/download-artifact@v4
        with:
          name: windows-installer
          path: release/windows/installer/

      - name: Create zip archive of Windows portable folder
        run: |
          zip -r release/windows/portable-windows.zip release/windows/portable  

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.1.1
          files: |
            release/android/split/app-arm64-v8a-release.apk
            release/android/split/app-armeabi-v7a-release.apk
            release/android/split/app-x86_64-release.apk
            release/android/app-release.aab
            release/android/app-release.apk
            release/windows/portable-windows.zip
            release/windows/installer/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}